/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/desk.glb 
*/

import React, { useEffect, useState, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useScreenContent } from './useScreenContent.js'
import { Select } from '@react-three/postprocessing'

export default function Desk({ setTooltipText, ...props}) {
  const { nodes, materials } = useGLTF('/models/desk.glb')
  //console.log("Loaded Nodes:", nodes)
  const { videoTextureLeft, videoTextureCenter, videoTextureRight } = useScreenContent()
  const [hovered, setHover] = useState(null)
  const hoverTimeout = useRef()

  // Handle hover events to show tooltip and change cursor
  const handleHover = (e, name, text) => {
    e.stopPropagation();
    clearTimeout(hoverTimeout.current);
    // Prevent redundant updates
    if (hovered !== name) {
      console.log("Hovering over:", name);
      setHover(name);
      document.body.style.cursor = 'pointer';
      setTooltipText(text);
    }
  };

    const handleUnhover = (e) => {
    if (e) e.stopPropagation();
    hoverTimeout.current = setTimeout(() => {
      setHover(null);
      document.body.style.cursor = 'auto';
      setTooltipText(null);
    }, 50);
  }

  useEffect(() => {
    const allTextures = [videoTextureLeft, videoTextureCenter, videoTextureRight]
    console.log("Setting up video textures for autoplay");
    allTextures.forEach((texture) => {
        if (texture) {
          texture.image.playsInline = true;
          texture.image.muted = true;
          texture.image.play().catch(e => console.log("Autoplay blocked:", e));
        }
      });
    }, [videoTextureLeft, videoTextureCenter, videoTextureRight]);

  return (
      <group {...props} dispose={null}>

        {/* --- DESK --- */}
        <group position={[0, 0.717, 0]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.Plank_1.geometry} material={materials.Mat_BleuNoir} />
          <mesh geometry={nodes.Plank_2.geometry} material={materials.Mat_OAK} />
        </group>
        <mesh geometry={nodes.Right_Box.geometry} material={materials.Mat_BleuNoir} position={[0.57, 0.35, 0.075]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.Left_Box.geometry} material={materials.Mat_BleuNoir} position={[-0.57, 0.35, 0.075]} rotation={[Math.PI, 0, Math.PI]} />

        {/* --- LEFT DRAWERS --- */}
        <group position={[-0.57, 0.114, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.Drawer_L_0_1.geometry} material={materials.Mat_BleuNoir} />
          <mesh geometry={nodes.Drawer_L_0_2.geometry} material={materials.Mat_InsideWhite} />
        </group>
        <group position={[-0.57, 0.246, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.Drawer_L_1_1.geometry} material={materials.Mat_BleuNoir} />
          <mesh geometry={nodes.Drawer_L_1_2.geometry} material={materials.Mat_InsideWhite} />
        </group>
        <group position={[-0.57, 0.379, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.Drawer_L_2_1.geometry} material={materials.Mat_BleuNoir} />
          <mesh geometry={nodes.Drawer_L_2_2.geometry} material={materials.Mat_InsideWhite} />
        </group>
        <group position={[-0.57, 0.512, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.Drawer_L_3_1.geometry} material={materials.Mat_BleuNoir} />
          <mesh geometry={nodes.Drawer_L_3_2.geometry} material={materials.Mat_InsideWhite} />
        </group>
        <group position={[-0.57, 0.644, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.Drawer_L_4_1.geometry} material={materials.Mat_BleuNoir} />
          <mesh geometry={nodes.Drawer_L_4_2.geometry} material={materials.Mat_InsideWhite} />
        </group>

        {/* --- RIGHT DRAWERS --- */}
        <group position={[0.57, 0.114, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.Drawer_R_0_1.geometry} material={materials.Mat_BleuNoir} />
          <mesh geometry={nodes.Drawer_R_0_2.geometry} material={materials.Mat_InsideWhite} />
        </group>
        <group position={[0.57, 0.246, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.Drawer_R_1_1.geometry} material={materials.Mat_BleuNoir} />
          <mesh geometry={nodes.Drawer_R_1_2.geometry} material={materials.Mat_InsideWhite} />
        </group>
        <group position={[0.57, 0.379, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.Drawer_R_2_1.geometry} material={materials.Mat_BleuNoir} />
          <mesh geometry={nodes.Drawer_R_2_2.geometry} material={materials.Mat_InsideWhite} />
        </group>
        <group position={[0.57, 0.512, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.Drawer_R_3_1.geometry} material={materials.Mat_BleuNoir} />
          <mesh geometry={nodes.Drawer_R_3_2.geometry} material={materials.Mat_InsideWhite} />
        </group>
        <group position={[0.57, 0.644, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh geometry={nodes.Drawer_R_4_1.geometry} material={materials.Mat_BleuNoir} />
          <mesh geometry={nodes.Drawer_R_4_2.geometry} material={materials.Mat_InsideWhite} />
        </group>

        {/* --- SCREENS --- */}
        <mesh geometry={nodes.RodStand_Left.geometry} material={materials.Mat_DarkMetallic} position={[-0.639, 0.928, -0.187]}></mesh>
        <group position={[-0.532, 1.025, -0.016]} rotation={[0, 0.431, 0]}
        onPointerOver={(e) => handleHover(e, 'leftScreen', 'Left Screen')}
        onPointerOut={() => {handleUnhover()}} >
          <mesh geometry={nodes.Screen_Left_1.geometry} material={materials.Mat_DarkPlastic} />
          <Select enabled={hovered === 'leftScreen'}>
            <group>
              <mesh 
              geometry={nodes.Screen_Left_2.geometry} 
              material={materials.Mat_Screen_Left} >
                <planeGeometry args={[0.4,0.25]} />
                <meshBasicMaterial map={videoTextureLeft} toneMapped={false} />
              </mesh>
            </group>
          </Select>
        </group>
        <mesh geometry={nodes.ScreenStand_Left.geometry} material={materials.Mat_DarkMetallic} position={[-0.718, 0.714, -0.296]} />
        <mesh geometry={nodes.StandToScreen_Left.geometry} material={materials['Mat_BleuNoir.001']} position={[-0.549, 1.02, -0.063]} rotation={[0, 0.431, 0]} />
        <mesh geometry={nodes.RodStand_Right.geometry} material={materials.Mat_DarkMetallic} position={[0.649, 0.926, -0.178]} rotation={[0.079, -1.267, 0.015]} />
        <group position={[0.532, 1.025, -0.016]} rotation={[0, -0.849, -Math.PI / 2]}
        onPointerOver={(e) => handleHover(e, 'rightScreen', 'Right Screen')}
        onPointerOut={() => {handleUnhover()}}>
          <Select enabled={hovered === 'rightScreen'}>
            <group >
              <mesh geometry={nodes.Screen_Right_1.geometry} material={materials.Mat_DarkPlastic} />
              <mesh 
              rotation={[0, 0, Math.PI / 2]} 
              geometry={nodes.Screen_Right_2.geometry} 
              material={materials.Mat_Screen_Right}>
                <planeGeometry args={[0.25, 0.4]} />
                <meshBasicMaterial map={videoTextureRight} toneMapped={false} />
              </mesh>
            </group>
          </Select>
        </group>
        <mesh geometry={nodes.ScreenStand_Right.geometry} material={materials.Mat_DarkMetallic} position={[0.734, 0.714, -0.296]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.StandToScreen_Right.geometry} material={materials['Mat_BleuNoir.002']} position={[0.564, 1.004, -0.057]} rotation={[0, -0.849, -Math.PI / 2]} />
        <group position={[0, 1, -0.128]}
        onPointerOver={(e) => handleHover(e, 'centerScreen', 'Center Screen')}
        onPointerOut={() => {handleUnhover()}}>
          <Select enabled={hovered === 'centerScreen'}>
            <group >
              <mesh geometry={nodes.Screen_Central_1.geometry} material={materials.Mat_Metallic_Grey} />
              <mesh 
              geometry={nodes.Screen_Central_2.geometry} 
              material={materials.Mat_Screen_Center} >
                <planeGeometry args={[0.5,0.3]} />
                <meshBasicMaterial map={videoTextureCenter} toneMapped={false} />
              </mesh>
            </group>
          </Select>
        </group>
        <group position={[0, 0.886, -0.263]}>
          <mesh geometry={nodes.ScreenStand_Central_1.geometry} material={materials.Mat_Metallic_Grey} />
          <mesh geometry={nodes.ScreenStand_Central_2.geometry} material={materials.Mat_DarkPlastic} />
        </group>
        <mesh geometry={nodes.StandToScreen_Central.geometry} material={materials.Mat_DarkPlastic} position={[0, 1.005, -0.203]} />

        {/* --- BOOKS --- */}
        <group 
        onPointerOver={(e) => handleHover(e, 'book', 'Books')}
        onPointerOut={(e) => {handleUnhover()}}
        >
          <Select enabled ={hovered === 'book'}>
            <group position={[-0.599, 0.745, 0.241]} rotation={[0, 0.414, 0]}>
              <mesh geometry={nodes.Book0_1.geometry} material={materials.Mat_DarkPlastic} />
              <mesh geometry={nodes.Book0_2.geometry} material={materials.Mat_InsideWhite} />
            </group>
            <group position={[-0.599, 0.765, 0.241]} rotation={[0, -0.334, 0]}>
              <mesh geometry={nodes.Book1_1.geometry} material={materials.Mat_DarkPlastic} />
              <mesh geometry={nodes.Book1_2.geometry} material={materials.Mat_InsideWhite} />
            </group>
            <group position={[-0.599, 0.794, 0.239]} rotation={[0, -0.25, 0]}>
              <mesh geometry={nodes.Book2_1.geometry} material={materials.Mat_DarkPlastic} />
              <mesh geometry={nodes.Book2_2.geometry} material={materials.Mat_InsideWhite} />
            </group>
            <group position={[-0.593, 0.824, 0.241]} rotation={[0, -0.25, 0]}>
              <mesh geometry={nodes.Book3_1.geometry} material={materials.Mat_Book0} />
              <mesh geometry={nodes.Book3_2.geometry} material={materials.Mat_InsideWhite} />
            </group>
            <group position={[-0.608, 0.844, 0.237]} rotation={[0, -0.014, 0]}>
              <mesh geometry={nodes.Book4_1.geometry} material={materials.Mat_Book1} />
              <mesh geometry={nodes.Book4_2.geometry} material={materials.Mat_InsideWhite} />
            </group>
            <group position={[-0.621, 0.864, 0.234]} rotation={[0, 0.116, 0]}>
              <mesh geometry={nodes.Book5_1.geometry} material={materials.Mat_Book2} />
              <mesh geometry={nodes.Book5_2.geometry} material={materials.Mat_InsideWhite} />
            </group>
          </Select>
        </group>
        {/* --- ACCESSORIES --- */}
        <group 
        onPointerOver={(e) => handleHover(e, 'speaker', 'Speakers')}
        onPointerOut={(e) => {handleUnhover()}}
        >
          <Select enabled ={hovered === 'speaker'}>
            <group position={[-0.36, 0.812, -0.077]} rotation={[0, 0.214, 0]}>
              <mesh geometry={nodes.Speaker_Left_1.geometry} material={materials.Mat_GlossyDarkGrey} />
              <mesh geometry={nodes.Speaker_Left_2.geometry} material={materials.Mat_VarnishedWood} />
              <mesh geometry={nodes.Speaker_Left_3.geometry} material={materials.Mat_Metallic_Grey} />
            </group>
            <group position={[0.318, 0.812, -0.093]} rotation={[0, -0.258, 0]}>
              <mesh geometry={nodes.Speaker_Right_1.geometry} material={materials['Mat_GlossyDarkGrey.001']} />
              <mesh geometry={nodes.Speaker_Right_2.geometry} material={materials['Mat_VarnishedWood.001']} />
              <mesh geometry={nodes.Speaker_Right_3.geometry} material={materials['Mat_Metallic_Grey.001']} />
            </group>
          </Select>
        </group>
        <group position={[0.03, 0.746, 0.108]}>
          <mesh geometry={nodes.Keyboard_1.geometry} material={materials.Mat_DarkMetallic} />
          <mesh geometry={nodes.Keyboard_2.geometry} material={materials['Mat_DarkMetallic.002']} />
          <mesh geometry={nodes.Keyboard_3.geometry} material={materials.Mat_DarkPlastic} />
          <mesh geometry={nodes.Keyboard_4.geometry} material={materials['Mat_DarkPlastic.001']} />
          <mesh geometry={nodes.Keyboard_5.geometry} material={materials['Mat_DarkPlastic.003']} />
        </group>
        <mesh geometry={nodes.Mouse.geometry} material={materials.Mat_DarkPlastic} position={[0.173, 0.741, 0.18]} />
        <mesh geometry={nodes.MousePad.geometry} material={materials.Mat_MousePad} position={[0, 0.735, 0.2]} />
      </group>
  )
}

useGLTF.preload('/desk.glb')
