/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/desk.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Desk(props) {
  const { nodes, materials } = useGLTF('/models/desk.glb') // <--- NOTE: I added /models/ path here just in case
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.MousePad.geometry} material={materials.Mat_MousePad} position={[0, 0.735, 0.2]} />
      <group position={[0.03, 0.746, 0.108]}>
        <mesh geometry={nodes.Cube021.geometry} material={materials.Mat_DarkMetallic} />
        <mesh geometry={nodes.Cube021_1.geometry} material={materials['Mat_DarkMetallic.002']} />
        <mesh geometry={nodes.Cube021_2.geometry} material={materials.Mat_DarkPlastic} />
        <mesh geometry={nodes.Cube021_3.geometry} material={materials['Mat_DarkPlastic.001']} />
        <mesh geometry={nodes.Cube021_4.geometry} material={materials['Mat_DarkPlastic.003']} />
      </group>
      <mesh geometry={nodes.Mouse.geometry} material={materials.Mat_DarkPlastic} position={[0.173, 0.741, 0.18]} />
      <group position={[-0.599, 0.745, 0.241]} rotation={[0, 0.414, 0]}>
        <mesh geometry={nodes.Cube061.geometry} material={materials.Mat_DarkPlastic} />
        <mesh geometry={nodes.Cube061_1.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[-0.599, 0.765, 0.241]} rotation={[0, -0.334, 0]}>
        <mesh geometry={nodes.Cube062.geometry} material={materials.Mat_DarkPlastic} />
        <mesh geometry={nodes.Cube062_1.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[-0.599, 0.794, 0.239]} rotation={[0, -0.25, 0]}>
        <mesh geometry={nodes.Cube063.geometry} material={materials.Mat_DarkPlastic} />
        <mesh geometry={nodes.Cube063_1.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[-0.593, 0.824, 0.241]} rotation={[0, -0.25, 0]}>
        <mesh geometry={nodes.Cube064.geometry} material={materials.Mat_Book0} />
        <mesh geometry={nodes.Cube064_1.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[-0.608, 0.844, 0.237]} rotation={[0, -0.014, 0]}>
        <mesh geometry={nodes.Cube065.geometry} material={materials.Mat_Book1} />
        <mesh geometry={nodes.Cube065_1.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[-0.621, 0.864, 0.234]} rotation={[0, 0.116, 0]}>
        <mesh geometry={nodes.Cube066.geometry} material={materials.Mat_Book2} />
        <mesh geometry={nodes.Cube066_1.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[0, 0.717, 0]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Plank_1.geometry} material={materials.Mat_BleuNoir} />
        <mesh geometry={nodes.Plank_2.geometry} material={materials.Mat_OAK} />
      </group>
      <mesh geometry={nodes.Right_Box.geometry} material={materials.Mat_BleuNoir} position={[0.57, 0.35, 0.075]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Left_Box.geometry} material={materials.Mat_BleuNoir} position={[-0.57, 0.35, 0.075]} rotation={[Math.PI, 0, Math.PI]} />
      <group position={[-0.57, 0.114, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Drawer_L_0_1.geometry} material={materials.Mat_BleuNoir} />
        <mesh geometry={nodes.Drawer_L_0_2.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[-0.57, 0.246, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Drawer_L_1_1.geometry} material={materials.Mat_BleuNoir} />
        <mesh geometry={nodes.Drawer_L_1_2.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[-0.57, 0.379, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Drawer_L_2_1.geometry} material={materials.Mat_BleuNoir} />
        <mesh geometry={nodes.Drawer_L_2_2.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[-0.57, 0.512, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Drawer_L_3_1.geometry} material={materials.Mat_BleuNoir} />
        <mesh geometry={nodes.Drawer_L_3_2.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[-0.57, 0.644, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Drawer_L_4_1.geometry} material={materials.Mat_BleuNoir} />
        <mesh geometry={nodes.Drawer_L_4_2.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[0.57, 0.114, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Drawer_R_0_1.geometry} material={materials.Mat_BleuNoir} />
        <mesh geometry={nodes.Drawer_R_0_2.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[0.57, 0.246, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Drawer_R_1_1.geometry} material={materials.Mat_BleuNoir} />
        <mesh geometry={nodes.Drawer_R_1_2.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[0.57, 0.379, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Drawer_R_2_1.geometry} material={materials.Mat_BleuNoir} />
        <mesh geometry={nodes.Drawer_R_2_2.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[0.57, 0.512, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Drawer_R_3_1.geometry} material={materials.Mat_BleuNoir} />
        <mesh geometry={nodes.Drawer_R_3_2.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <group position={[0.57, 0.644, 0.3]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Drawer_R_4_1.geometry} material={materials.Mat_BleuNoir} />
        <mesh geometry={nodes.Drawer_R_4_2.geometry} material={materials.Mat_InsideWhite} />
      </group>
      <mesh geometry={nodes.RodStand_Left.geometry} material={materials.Mat_DarkMetallic} position={[-0.639, 0.928, -0.187]} />
      <group position={[-0.532, 1.025, -0.016]} rotation={[0, 0.431, 0]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials.Mat_DarkPlastic} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials.Mat_Screen_Left} />
      </group>
      <mesh geometry={nodes.ScreenStand_Left.geometry} material={materials.Mat_DarkMetallic} position={[-0.718, 0.714, -0.296]} />
      <mesh geometry={nodes.StandToScreen_Left.geometry} material={materials['Mat_BleuNoir.001']} position={[-0.549, 1.02, -0.063]} rotation={[0, 0.431, 0]} />
      <mesh geometry={nodes.RodStand_Right.geometry} material={materials.Mat_DarkMetallic} position={[0.649, 0.926, -0.178]} rotation={[0.079, -1.267, 0.015]} />
      <group position={[0.532, 1.025, -0.016]} rotation={[0, -0.849, -Math.PI / 2]}>
        <mesh geometry={nodes.Cube016.geometry} material={materials.Mat_DarkPlastic} />
        <mesh geometry={nodes.Cube016_1.geometry} material={materials.Mat_Screen_Right} />
      </group>
      <mesh geometry={nodes.ScreenStand_Right.geometry} material={materials.Mat_DarkMetallic} position={[0.734, 0.714, -0.296]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.StandToScreen_Right.geometry} material={materials['Mat_BleuNoir.002']} position={[0.564, 1.004, -0.057]} rotation={[0, -0.849, -Math.PI / 2]} />
      <group position={[0, 1, -0.128]}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials.Mat_Metallic_Grey} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials.Mat_Screen_Center} />
      </group>
      <group position={[0, 0.886, -0.263]}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.Mat_Metallic_Grey} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials.Mat_DarkPlastic} />
      </group>
      <mesh geometry={nodes.StandToScreen_Central.geometry} material={materials.Mat_DarkPlastic} position={[0, 1.005, -0.203]} />
      <group position={[-0.36, 0.812, -0.077]} rotation={[0, 0.214, 0]}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials.Mat_GlossyDarkGrey} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.Mat_VarnishedWood} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials.Mat_Metallic_Grey} />
      </group>
      <group position={[0.318, 0.812, -0.093]} rotation={[0, -0.258, 0]}>
        <mesh geometry={nodes.Cylinder012.geometry} material={materials['Mat_GlossyDarkGrey.001']} />
        <mesh geometry={nodes.Cylinder012_1.geometry} material={materials['Mat_VarnishedWood.001']} />
        <mesh geometry={nodes.Cylinder012_2.geometry} material={materials['Mat_Metallic_Grey.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/desk.glb')